### PR TITLE
Add activity controller and feature specs

### PR DESCRIPTION
**Pull request by monicao**
… In class W7D4

@fourmojocto Please review when you get a chance.

### CODE REVIEW

**Comment by davidvandusen** [comment]
@monicao Any idea why this is still open?

**Comment by monicao** [comment]
@davidvandusen I am not sure. A long time ago, I attempted to fix the feature specs. Guess this got lost between the cracks and nobody reviewed it. I'm guessing the tests are no longer relevant. Feel free to close if the PR no longer holds any value.

**Comment by davidvandusen** [comment]
The tests look valuable, but there have been some changes that cause them to fail. I merged master into this branch locally and it looks like changes to the UI and the day unlocking feature cause these tests to break.

If you'd like to get these tests to pass against the current master, I'd be happy to merge them in. Otherwise I'll move the card (or make a card) for students to do to reproduce these tests.

**Comment by monicao** [comment]
I think this would be a great thing for one of the more advanced students to fix, so they can get some exposure to feature tests.

**Comment by davidvandusen** [comment]
Ok. Moving the card to the "Tests Needed" lane. I'm going to be looking for students who are interested in learning about writing good test suites to help us get some better coverage.

Closing, but adding a comment to the card to reopen when these tests are fixed.

**Pull request closed without merging**
